name: Compress Resourcepack on Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r "HCSkyblock-${{ github.ref_name }}.zip" . \
          -x ".git/*" ".github/*" "gallery/*"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: "HCSkyblock-${{ github.ref_name }}.zip"
          body_path: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
